document.write("<div class=\"header\">");
document.write("  <div class=\"firstpart\">");
document.write("    <div class=\"lang\">");
document.write("<a href=\"#\"><img src=\"../../images/sources/kz.png\" alt=\"\"></a>");
document.write("<a href=\"../../eng.html\"><img src=\"../../images/sources/en.png\" alt=\"\"></a>");
document.write("<a href=\"../../index.html\"><img src=\"../../images/sources/ru.png\" alt=\"\"></a>");
document.write("    </div>");
document.write("    <div class=\"ticker\">");
document.write("<marquee>Международная школа «Мирас» города Астана обеспечивает качественное образование, основанное на интеграции международных и казахстанских образовательных стандартов, способствующее формированию интернационального мышления,   содействующее всестороннему развитию студентов,  приобретению ими навыков непрерывного самообразования в стимулирующей и благоприятной школьной среде.</marquee>");
document.write("    </div>");
document.write("    <div class=\"socnet\">");
document.write("<img src=\"../../images/sources/fb.png\" alt=\"\">");
document.write("<img src=\"../../images/sources/inst.png\" alt=\"\">");
document.write("<img src=\"../../images/sources/wa.png\" alt=\"\">");
document.write("    </div>");
document.write("  </div>");
document.write("  <div class=\"secondpart\">");
document.write("<div class=\"logos\">");
document.write("    <div class=\"nneflogo\">");
document.write("      <a href=\"https://foundation.kz/\"><img src=\"../../images/sources/nnef.png\" alt=\"1\"></a>");
document.write("    </div>");
document.write("    <div class=\"miraslogo\">");
document.write("      <a href=\"https://miras-astana.kz/\"><img src=\"../../images/sources/miras20.png\" alt=\"2\"></a>");
document.write("    </div>");
document.write("</div>");
document.write("<div class=\"schoolname\">");
document.write("<span>MIRAS INTERNATIONAL SCHOOL</span>");
document.write("<span>The Branch of Nursultan Nazarbayev Educational Foundation</span>");
document.write("</div>");
document.write("<div class=\"partners\">");
document.write("<div class=\"partners_line\">");
document.write("  <div class=\"partner_pic\">");
document.write("    <a href=\"https://www.ibo.org/\"><img src=\"../../images/sources/ib.png\" alt=\"\"></a>");
document.write("  </div>");
document.write("  <div class=\"partner_pic\">");
document.write("    <a href=\"https://www.cois.org/\"><img src=\"../../images/sources/cis.png\" alt=\"\"></a>");
document.write("  </div>");
document.write("  <div class=\"partner_pic\">");
document.write("    <a href=\"https://www.ecis.org/\"><img src=\"../../images/sources/ecis.png\" alt=\"\"></a>");
document.write("  </div>");
document.write("</div>");
document.write("<div class=\"partners_line\">");
document.write("  <div class=\"partner_pic\">");
document.write("    <a href=\"https://www.neasc.org/\"><img src=\"../../images/sources/neasc.png\" alt=\"\"></a>");
document.write("  </div>");
document.write("  <div class=\"partner_pic\">");
document.write("    <a href=\"http://ibsa.su/\"><img src=\"../../images/sources/asmb.jpg\" alt=\"\"></a>");
document.write("  </div>");
document.write("  <div class=\"partner_pic\">");
document.write("    <a href=\"https://en.unesco.org/\"><img src=\"../../images/sources/unesco.png\" alt=\"\"></a>");
document.write("  </div>");
document.write("</div>");
document.write("</div>");
document.write("<div class=\"contacts\">");
document.write("<div class=\"telephone\"><i class=\"fas fa-phone\"></i><span>+7 (7172) </span>369867<br>");
document.write("  <span class=\"telissue\">+7 (7172) </span>369868");
document.write("</div>");
document.write("<div class=\"address\">");
document.write("  <span><i class=\"fas fa-map-marker-alt\"></i>Kuishi Dina st. 34<br> Nur-Sultan, Kazakhstan</span>");
document.write("</div>");
document.write("<div class=\"email\">");
document.write("<span><i class=\"far fa-envelope\"></i><a href=\"mailto:info@miras-astana.kz\">info@miras-astana.kz</a></span>");
document.write("</div>");
document.write("</div>");
document.write("  </div>");
document.write("</div>");
document.write("<div class=\"menu\">");
document.write("  <nav class=\"navbar navbar-expand navbar-light\" style=\"background-color: #2669d2;\">");
//document.write("    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">");
//document.write("      <span class=\"navbar-toggler-icon\"></span>");
//document.write("    </button>");
document.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">");
document.write("      <ul class=\"navbar-nav mr-auto\">");
document.write("        <li class=\"nav-item active\">");
document.write("          <a class=\"nav-link\" href=\"../../index.html\" style=\"color: white;\"><i class=\"fas fa-home\"></i><span class=\"sr-only\">(current)</span></a>");
document.write("        </li>");
document.write("        <li class=\"nav-item dropdown\">");
document.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">");
document.write("            О школе");
document.write("          </a>");
document.write("          <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">");
document.write("            <a class=\"dropdown-item\" href=\"about-foundation.html\">Информация о Фонде</a>");
document.write("            <a class=\"dropdown-item\" href=\"administration.html\">Администрация</a>");
document.write("            <a class=\"dropdown-item\" href=\"awards.html\">Преимущества и достижения</a>");
document.write("            <a class=\"dropdown-item\" href=\"instagram.html\">Галерея</a>");
document.write("            <a class=\"dropdown-item\" href=\"stem.html\">STEM</a>");
document.write("          </div>");
document.write("                  </li>");
document.write("        <li class=\"nav-item dropdown\">");
document.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">");
document.write("            Поступающим");
document.write("          </a>");
document.write("          <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">");
document.write("            <a class=\"dropdown-item\" href=\"tarif.html\">Тарифы</a>");
document.write("            <a class=\"dropdown-item\" href=\"procedure.html\">Правила приема</a>");
document.write("            <a class=\"dropdown-item\" href=\"https://mirasastana-my.sharepoint.com/:f:/g/personal/yerlan_miras-astana_kz/Erxr-ko6dnhJmJKUaGXu9S8BjA1jK84p5fQp5JMCSykJsA?e=Ueb1JI\" target=\"_blank\">Анкета</a>");
document.write("            <a class=\"dropdown-item\" href=\"equipment_requirements.html\">Список учебных принадлежностей</a>");
document.write("            <a class=\"dropdown-item\" href=\"activities_all.html\">Кружки</a>");
document.write("            <a class=\"dropdown-item\" href=\"uniform.html\">Школьная форма</a>");
document.write("            <a class=\"dropdown-item\" href=\"#\">Виртуальный гид</a>");
document.write("          </div>");
document.write("        </li>");
document.write("        <li class=\"nav-item dropdown\">");
document.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">");
document.write("            Студентам");
document.write("          </a>");
document.write("          <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">");
document.write("            <a class=\"dropdown-item\" href=\"activities_all.html\">Кружки НШ/ОШ</a>");
document.write("            <a class=\"dropdown-item\" href=\"calendar.html\">Календарь</a>");
document.write("          </div>");
document.write("        </li>");
document.write("        <li class=\"nav-item dropdown\">");
document.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">");
document.write("            Родителям");
document.write("          </a>");
document.write("          <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">");
document.write("            <a class=\"dropdown-item\" href=\"#\">Детский сад</a>");
document.write("              <div class=\"dropdown-menu\">");
document.write("                          <a class=\"dropdown-item\" href=\"welcome_preschool.html\">Приветствие координатора по дошкольному воспитанию</a>");
document.write("                          <a class=\"dropdown-item\" href=\"rules_preschool.html\">Правила детского сада</a>");
document.write("                          <a class=\"dropdown-item\" href=\"food_preschool.html\">Недельное меню</a>");
document.write("                          <a class=\"dropdown-item\" href=\"newsletter_preschool.html\">Информационный бюллетень</a>");
document.write("                          <a class=\"dropdown-item\" href=\"activities_preschool.html\">Кружки/секции</a>");
document.write("                          <!--<a class=\"dropdown-item submenu\" href=\"#\">2-й уровень</a>-->");
document.write("                        </div>");
document.write("            <a class=\"dropdown-item\" href=\"#\">Начальная школа</a>");
document.write("            <div class=\"dropdown-menu\">");
document.write("                        <a class=\"dropdown-item\" href=\"welcome_primary.html\">Приветствие директора</a>");
document.write("                        <a class=\"dropdown-item\" href=\"calendar.html\">Календарь школы</a>");
document.write("                        <a class=\"dropdown-item\" href=\"../../download/PS SP HB 2019 Rus.pdf\" target=\"_blank\">Руководство для родителей</a>");
document.write("                        <a class=\"dropdown-item\" href=\"#\">Правила и политики школы</a>");
document.write("                        <a class=\"dropdown-item\" href=\"equipment_requirements_primary.html\">Список учебных принадлежностей</a>");
document.write("                        <a class=\"dropdown-item\" href=\"uniform_primary.html\">Школьная форма</a>");
document.write("                        <a class=\"dropdown-item\" href=\"program_primary.html\">Программа Начальной школы</a>");
document.write("                        <a class=\"dropdown-item\" href=\"newsletter_primary.html\">Информационный бюллетень</a>");
document.write("                        <a class=\"dropdown-item\" href=\"food_primary.html\">Недельное меню</a>");
document.write("                        <!--<a class=\"dropdown-item submenu\" href=\"#\">2-й уровень</a>-->");
document.write("                      </div>");
document.write("            <a class=\"dropdown-item\" href=\"#\">Старшая школа</a>");
document.write("            <div class=\"dropdown-menu\">");
document.write("                        <a class=\"dropdown-item\" href=\"welcome_secondary.html\">Приветствие директора</a>");
document.write("                        <a class=\"dropdown-item\" href=\"calendar.html\">Календарь школы</a>");
document.write("                        <a class=\"dropdown-item\" href=\"../../download/Secondary School SP Handbook 19-20 R.pdf\" target=\"_blank\">Руководство для родителей</a>");
document.write("                        <a class=\"dropdown-item\" href=\"#\">Правила и политики школы</a>");
document.write("                        <a class=\"dropdown-item\" href=\"equipment_requirements_secondary.html\">Список учебных принадлежностей</a>");
document.write("                        <a class=\"dropdown-item\" href=\"uniform_secondary.html\">Школьная форма</a>");
document.write("                        <a class=\"dropdown-item\" href=\"program_secondary.html\">Программа Старшей школы</a>");
document.write("                        <a class=\"dropdown-item\" href=\"../../download/Diploma Handbook 2019-2020.pdf\" target=\"_blank\">Дипломная программа</a>");
document.write("                        <a class=\"dropdown-item\" href=\"newsletter_secondary.html\">Информационный бюллетень</a>");
document.write("                        <a class=\"dropdown-item\" href=\"food_secondary.html\">Недельное меню</a>");
document.write("                        <!--<a class=\"dropdown-item submenu\" href=\"#\">2-й уровень</a>-->");
document.write("                      </div>");
document.write("                    </div>");
document.write("        </li>");
document.write("        <li class=\"nav-item\">");
document.write("        <a class=\"nav-link\" href=\"https://www.efns.kz/\">Французская школа</a>");
document.write("      </li>");
document.write("      </ul>");
document.write("    </div>");
document.write("  </nav>");
document.write("</div>");
